#!/bin/bash

trap "killall cyclical_linearizability; exit" SIGINT SIGTERM

cargo build --features=env_logger --release --bin cyclical_linearizability
while [[ $? -eq 0 ]]; do
  RUST_LOG=sled=info target/release/cyclical_linearizability &
  sleep `shuf -i 5-15 -n 1`
  kill $!
  # TODO sometimes randomly truncate the file/corrupt part of it
  # linearizability should still be preserved, and recovery should halt
  # past the corruption.
done
