#!/bin/sh
set -e 

export RUSTFLAGS="-Z sanitizer=leak"

cargo build \
  --bin=stress \
  --features="stress" \
  --target x86_64-unknown-linux-gnu \
  --verbose

sudo ./target/x86_64-unknown-linux-gnu/debug/stress
