#!/bin/sh
set -e

export RUSTFLAGS="-Z sanitizer=$1"
export TSAN_OPTIONS="suppressions=hack/suppressions.cfg"

rm target/x86_64-unknown-linux-gnu/debug/stress2

rustup run nightly-2017-07-06-x86_64-unknown-linux-gnu cargo build \
  --bin=stress2 \
  --features="stress" \
  --target x86_64-unknown-linux-gnu \
  --verbose

target/x86_64-unknown-linux-gnu/debug/stress2
